export const CHANGE_AMIIBOS = 'CHANGE_AMIIBOS';
export const CHANGE_LIKED_AMIIBOS = 'CHANGE_LIKED_AMIIBOS';
export const CHANGE_GAMESERIES = 'CHANGE_GAMESERIES';
export const CHANGE_CHARACTERS = 'CHANGE_CHARACTERS';
export const CHANGE_ACTIVE_GAMESERIES = 'CHANGE_ACTIVE_GAMESERIES';
export const CHANGE_ACTIVE_CHARACTER = 'CHANGE_ACTIVE_CHARACTER';
export const TOGGLE_LIKE = 'TOGGLE_LIKE';
